apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-game-api-nest
  namespace: beer-game
spec:
  selector:
    matchLabels:
      app: beer-game-api-nest
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%  
  template:
    metadata:
      labels:
        app: beer-game-api-nest
    spec:
      containers:
        - name: beer-game-api-nest
          image: localhost:5000/beer-game-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: server
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: v1/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: v1/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: DB_HOST
              value: beer-game-mysql.default
            - name: DB_USER
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: beer-game-api-nest
  namespace: beer-game
  labels:
    app: beer-game-api-nest
spec:
  ports:
    - port: 8080
      name: server
  selector:
    app: beer-game-api-nest
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beer-game-api-nest
  namespace: beer-game
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: beer-game-api-nest
                port:
                  number: 8080