name: Build 

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push Docker image
      uses: docker/build-push-action@1
      with:
        username: ${{ github.actor }}
        password: ${{ screts.GITHUB_TOKEN }}
        registry: docker.pkq.github.com
        repository: LeonFelipeCordero/beer-game-api-nest/beer-game
        tag_with_ref: true
  