name: Beer game CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:latest

    strategy:
      matrix:
        node-version: [15.x]
    
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_USER: beer-game
          MYSQL_PASSWORD: beer-game
          MYSQL_DATABASE: beer-game
          MYSQL_ROOT_PASSWORD: beer-game
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installation
      run: yarn
    - name: Unit Tests
      run: yarn test
    - name: Integration Tests
      env:
        DB_HOST: mysql
      run: yarn test:e2e
  